<%@ page language="java" contentType="text/xml; charset=UTF-8"
    pageEncoding="UTF-8"%>
<people>
	<person>
		<name>홍길동</name>
		<gender>남자</gender>
		<part>기타</part>
	</person>
	<person>
		<name>성춘향</name>
		<gender>여자</gender>
		<part>드럼</part>
	</person>
	<person>
		<name>이몽룡</name>
		<gender>남자</gender>
		<part>보컬</part>
	</person>
</people>